[package]
name = "rust-sorter"
version = "0.1.0"
edition = "2021"

[lib]
name = "sort"
path = "src/sort.rs"

[dependencies]
num-format = "0.4.0"
rand = "0.8.5"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "sorting_benchmark"
harness = false
